horizontal-pad=20
inner-pad=20
dpi-aware=no
width=40
lines=20
y-margin=50
placeholder=Search here...

font=Iosevka Comfy Motion Duo:size=16
# prompt="󰍉  "
prompt="M-x  "
terminal=foot
layer=overlay
icons-enabled=no

[colors]
# background=181818ff
# input=e7e7e7ff
# text=e7e7e7ff
# match=b0b0b0ff
# selection=505050ff
# selection-text=b0b0b0ff
# selection-match=b0b0b0ff
# border=505050ff
# placeholder=505050ff
# prompt=e7e7e7ff

background=000000ff
input=ffffffff
text=ffffffff
match=ffffffff
selection=2f447fff
selection-text=ffffffff
selection-match=ffffffff
border=505050ff
placeholder=989898ff
prompt=6ae4b9ff

[border]
width=2
radius=0
